### ISSUE TITLE
Nested data

### ISSUE THREAD

**Issue by Terrijoo** [Nucs/JsonSettings#11]
This might be a rather noobish question, but is there a way of writing/reading nested data?
Something like: 

```
{
  "Data": {
    "$type": "nucs.Collections.SafeDictionary`2[[System.String, mscorlib],[System.Object, mscorlib]], nucs.JsonSettings",
    "Test1": {
      "Option1": true,
      "Option2": "Bla"
    },
    "Test2": {
      "Option1": false,
      "Option2": "Another bla"
    }
  }
}

```

**Comment by Nucs** [comment]
If your intend is to read `Test1` or `Test2` without parsing it using this library then you can use [newtonsoft.json](https://github.com/JamesNK/Newtonsoft.Json) to do that as it is the backend serialization I used in this library.
see: https://dotnetfiddle.net/Kjcgmp

**Comment by Terrijoo** [comment]
That actually helped a bunch! Thanks!

**Comment by Nucs** [comment]
Also, I forgot to note that the library uses custom settings for conversion via newtonsoft.json.
If you intend to convert/parse the json into an c# object **outside** of the library, make sure to set the library's custom settings.
See [here](https://dotnetfiddle.net/cixLkS) how to set the settings as default
