### ISSUE TITLE
.WithEncryption not in Library?

### ISSUE THREAD

**Issue by GreggTri** [Nucs/JsonSettings#12]
I Downloaded the Library through NuGet and VS is stating that WithEncryption doesn't exist. my Package Manager Control didn't state that it screwed up the installation either so I'm not really sure what's going on.

**Comment by Nucs** [comment]
Make sure to have the proper `using` to have access to their extensions, VS by itself does not recommend them automatically.

```C#
using nucs.JsonSettings;
using nucs.JsonSettings.Fluent; //this is what you are missing

JsonSettings.Construct<SettingsBag>().WithEncryption("123").LoadNow("c:/file.json");

```

I would suggest you to get [Resharper](https://www.jetbrains.com/resharper/) as it really increases productivity and searches for extensions for you. alternatively good for vs extensions that do that.

**Comment by GreggTri** [comment]
ah, you're right. thank you for the help and advice. I'll definitely get that extension.
