### ISSUE TITLE
How can I not save certain properties?

### ISSUE THREAD

**Issue by JasonLandbridge** [Nucs/JsonSettings#13]
Hi, 

Is there a way to not save certain properties? I have the properties below but all of them are saved even though they are not virtual.  

I'm using the [autosave extension](https://github.com/Nucs/JsonSettings/wiki/Autosave-extension)

       public virtual Dictionary<string, bool> BattleResultFilters { get; set; } = new Dictionary<string, bool>
        {
            [nameof(IsAttackStrengthShown)] = false,
            [nameof(IsDefenseStrengthShown)] = false,
            [nameof(IsResourcesLostShown)] = false,
        };

        public bool IsAttackStrengthShown
        {
            get => BattleResultFilters[nameof(IsAttackStrengthShown)];
            set => BattleResultFilters[nameof(IsAttackStrengthShown)] = value;
        }
        public bool IsDefenseStrengthShown
        {
            get => BattleResultFilters[nameof(IsDefenseStrengthShown)];
            set => BattleResultFilters[nameof(IsDefenseStrengthShown)] = value;
        }

        public bool IsResourcesLostShown
        {
            get => BattleResultFilters[nameof(IsResourcesLostShown)];
            set => BattleResultFilters[nameof(IsResourcesLostShown)] = value;
        }`

Which is now saved to:

```
{
  "BattleResultFilters": {
    "IsAttackStrengthShown": true,
    "IsDefenseStrengthShown": true,
    "IsResourcesLostShown": true
  },
  "IsAttackStrengthShown": true,
  "IsDefenseStrengthShown": true,
  "IsResourcesLostShown": true
}
```
Any suggestions? Thank you in advance!

**Comment by JasonLandbridge** [comment]
Ah i figured it out!

Adding `[JsonIgnore]` above the property will not save the property and ignore it.

**Comment by Nucs** [comment]
Yup, adding `[JsonIgnore]` is the proper way to do it as the library uses `Newtonsoft.Json`.

**Comment by Nucs** [comment]
Althought it is worth mentioning that if you are using Autosave mechanism - it doesn't distinguish between ignored properties/fields and will perform save on changes anyways. I'll open an issue to that.
