### ISSUE TITLE
Issue with autosave

### ISSUE THREAD

**Issue by minimalisticMe** [Nucs/JsonSettings#14]
Hey, I'm having yome troubles with the autosave feature.

Let's say I have a simplified class for UserSettings.
```
using nucs.JsonSettings;

namespace SettingsClasses
{
    public class UserSettingsClass : JsonSettings
    {
        public override string FileName { get; set; } = "UserSettings.config";

        public UserSettingsClass()
        { }

        public UserSettingsClass(string fileName) : base(fileName)
        { }

        public string UserName { get; set; }
        public string UserId { get; set; }
    }
}
```

and I have a central place for my Settings that I load like this:
```
using nucs.JsonSettings;
using nucs.JsonSettings.Autosave;
using System.IO;

namespace SettingsClasses
{
    public class Settings : ISettings
    {
        private static readonly string UserSettingsPath = "UserSettings.config";  //relative path to executing file.

        public static UserSettingsClass UserSettings
        {
            get
            {
                UserSettingsClass userSettings;
                if (File.Exists(UserSettingsPath))
                {
                    userSettings = JsonSettings.Load<UserSettingsClass>(UserSettingsPath).EnableAutosave();
                }
                else
                {
                    userSettings = JsonSettings.Construct<UserSettingsClass>(UserSettingsPath).EnableAutosave();
                    userSettings.Save();
                }

                return userSettings;
            }
            set
            { }
        }
    }
}
```

Now when I call `Settings.UserSettings.UserName = "User";` in the main thread I would expect the following:

- Create a file called `UserSettings.config` if it does not exist (check)
- Load a file called `UserSettings.config` if it does exist (I think so, untested)
- Autosave a value, when changed (not working for me as in example above)

**Comment by Nucs** [comment]
During debugging, this message is outputted to console via Error stream:
> JsonSettings: During proxy creation of UserSettingsClass, no virtual properties were found which will make Autosaving redundant.

Make `UserName` and `UserId` virtual.
For the entire documentation about AutoSave, take a look at [the article in our wiki](https://github.com/Nucs/JsonSettings/wiki/Autosave-extension).

**Comment by minimalisticMe** [comment]
Thank you very much, your JsonSettings work like magic - I love it!
