### ISSUE TITLE
Forced to reload information

### ISSUE THREAD

**Issue by ghost1372** [Nucs/JsonSettings#15]
Hi Is there a way to force the settings to receive new information?
for example In Window A, I set the following changes: 
I define **JsonSettings.Load** at the top of each class
![Untitled](https://user-images.githubusercontent.com/9213496/109416557-3d18df80-79d4-11eb-8031-b06c5849dfbe.png)

```
Setting.IsFirstRun = true;
```

When I go to Window B, I get Old information instead of new information
`var newVal = Setting.IsFirstRun;`

If I use the following code where I want to get new information, the problem will be solved
```
Settings SettingX = JsonSettings.Load<Settings>().EnableAutosave();
var newVal = SettingX.IsFirstRun;
```
Is there a better way to get the latest changes without redefining the settings?

**Comment by Nucs** [comment]
There is no way to do that built in,
The design was to read json once, did not anticipate it to be changed and reloaded during runtime therefore there is no way to listen for changes - nor updating the object on the fly.
That shouldn't stop you from creating a class that does just that.
Listen to changes in that file using window's api (theres a managed way) and every time there is a change, reload it and store staticly (so the entire app reloads it once and only when its changed).
So when you ask for settings, you get "snapshot" of how the file looked at that moment.
Every time you need to do something with it, you can access the static provider and get the latest from them. or if you dont care about how old it is then just store the result in your object for later use.

**Comment by ghost1372** [comment]
thank you I understood
