### ISSUE TITLE
The difference between EnableIAutosave and EnableAutosave

### ISSUE THREAD

**Issue by ghost1372** [Nucs/JsonSettings#16]
What is the difference between EnableIAutosave and EnableAutosave?

```
Settings x  = JsonSettings.Load<Settings>().EnableAutosave();

ISettings x = JsonSettings.Load<Settings>().EnableIAutosave<ISettings>();
```
Also, is it possible to update the documentation and write a little clearer?

**Comment by Nucs** [comment]
One returns a wrapped Settings object,
The other wrapped Settings object where only ISettings is exposed.
Essentially for when you want to use interface vs class.
