### ISSUE TITLE
Update and continue development

### ISSUE THREAD

**Issue by ghost1372** [Nucs/JsonSettings#17]
This project has not been updated for more than 2 years and This is really a useful project
Since .NET Core 3 and 5 have been published during these 2 years and NewtonSoft.Json has been constantly updated, It is better to update the project.
Also, despite the .NET Core, is it possible for the AutoSave feature to be implemented internally without the need for a Castle?

**Comment by Nucs** [comment]
There are plenty of new things this project can become and changed for the better.

> AutoSave feature to be implemented internally without the need for a Castle?

.NET 5 and .NET core can work with Castle without issues.
Castle makes my life easier as they take care of the implementation and support throughout the new versions.

You actually CAN use a newer version of NewtonSoft.Json, my requirements are >1.xx so just upgrade just NewtonSoft.Json package and it'll use the latest :)

Nevertheless, I agree that the project needs a little spank and update.

**Comment by ghost1372** [comment]
Yes, I understand that it is possible to update, but in general I meant that It would be great if this project could be updated and get more features.
thanks for the reply🙏
