### ISSUE TITLE
[Feature Request] Support AutoSave for INotifyPropertyChanged, INotifyCollectionChanged

### ISSUE THREAD

**Issue by ghost1372** [Nucs/JsonSettings#18]
I want to save the value of the datagrid column width in the setting file
I used the following:

```
public class Configs : JsonSettings
    {
        public override string FileName { get; set; } = "config.json";

        public virtual double[] ColumnWidth { get; set; } = new double[5];
        public virtual string[] ColumnWidth3 { get; set; } = new string[5];
        public virtual DataGridLength[] ColumnWidth2 { get; set; } = new DataGridLength[5];
    }
```

`public Configs Settings = JsonSettings.Load<Configs>().EnableAutosave();
`

```
private void dataGrid_LayoutUpdated(object sender, EventArgs e)
        {
            for (int index = 0; index < dataGrid.Columns.Count; index++)
            {
                Settings.ColumnWidth2[index] = new DataGridLength(dataGrid.Columns[index].ActualWidth);
                Settings.ColumnWidth[index] = dataGrid.Columns[index].ActualWidth;
                Settings.ColumnWidth3[index] = dataGrid.Columns[index].ActualWidth.ToString();
            }
        }
```

If I use the message box, I can see that all the columns have the correct value

`MessageBox.Show(string.Join("; ", dataGrid.Columns.Select(column => column.ActualWidth)));`

![image](https://user-images.githubusercontent.com/9213496/114849234-ce151000-9df4-11eb-830c-3e792038a6ed.png)

But the setting file shows the wrong information
![Untitled](https://user-images.githubusercontent.com/9213496/114849187-c3f31180-9df4-11eb-91b4-99660e1636eb.png)

**Comment by Nucs** [comment]
Did it happen due to lack of file versioning protection as described in #19 (did it fail to load becuase json as older format different?)

**Comment by ghost1372** [comment]
@Nucs No 
I created a example project please take a look at it
By clicking on the button, the size of the columns is displayed correctly
But the same sizes are stored differently in the settings file
[WpfApp3.zip](https://github.com/Nucs/JsonSettings/files/6405286/WpfApp3.zip)

**Comment by Nucs** [comment]
The idea you were trying to achieve is using a settings file as a view model or partially as a view model.
So I've decided to implement support for `INotifyPropertyChanged` and `INotifyCollectionChanged`.

Please have a look at this self explanatory example: https://github.com/Nucs/JsonSettings/blob/master/examples/INotifyPropertyChangedExample.cs
Also added `IgnoreAutosaveAttribute`

So now your settings file should look:

``` C#
public class Configs : NotifiyingJsonSettings {
    public override string FileName { get; set; } = "config.json";

    private ObservableCollection<double> _columnWidth = new ObservableCollection<double>(Enumerable.Repeat(0d, count: 5));
    private ObservableCollection<DataGridLength> _columnWidth2 = new ObservableCollection<DataGridLength>(Enumerable.Repeat<DataGridLength>(default, count: 5));
    private ObservableCollection<string> _columnWidth3 = new ObservableCollection<string>(Enumerable.Repeat<string>(null, count: 5));

    public virtual ObservableCollection<double> ColumnWidth {
        get => _columnWidth;
        set {
            if (Equals(value, _columnWidth)) return;
            _columnWidth = value;
            OnPropertyChanged();
        }
    }

    public virtual ObservableCollection<string> ColumnWidth3 {
        get => _columnWidth3;
        set {
            if (Equals(value, _columnWidth3)) return;
            _columnWidth3 = value;
            OnPropertyChanged();
        }
    }

    public virtual ObservableCollection<DataGridLength> ColumnWidth2 {
        get => _columnWidth2;
        set {
            if (Equals(value, _columnWidth2)) return;
            _columnWidth2 = value;
            OnPropertyChanged();
        }
    }
}
```

This will trigger a save whenever the property (INotifyPropertyChanged) by calling OnPropertyChanged() from setter or one of the items inside the property (INotifyCollectionChanged) are changed.

**Comment by ghost1372** [comment]
thank you i will test it when nuget package is ready

**Comment by ghost1372** [comment]
@Nucs  i tested your sample code and column width is stored correctly but I see the 0s again. Is this normal?
![3](https://user-images.githubusercontent.com/9213496/116786498-38e06f80-aab4-11eb-9da6-1863771aa309.png)

**Comment by ghost1372** [comment]
I also noticed something strange If we run the example project I sent earlier with a change
```
private void Button_Click(object sender, RoutedEventArgs e)
        {
            Settings.MyProperty = "test";
        }
```
All information is stored correctly in the database 🤔
![3](https://user-images.githubusercontent.com/9213496/116787751-37ff0c00-aabb-11eb-9347-68ace5f0a7c0.gif)

**Comment by Nucs** [comment]
> but I see the 0s again. Is this normal?

I think Json.NET might be serializing the ObservableCollection<T>'s internal array instead of determining how many items to serialize using Count property.

> I also noticed something strange If we run the example project I sent earlier with a change

I think the binding for the column's widths is not working on the XAML level. 
Could you drop .zip you ran? thanks.

**Comment by ghost1372** [comment]
Run the program
Open the settings file in the text editor (vscode)
Click on the button 
You can see the changes
[WpfApp3.zip](https://github.com/Nucs/JsonSettings/files/6410881/WpfApp3.zip)

**Comment by Nucs** [comment]
I initially assumed you would bind the column widths by templating the columns.
Anyways, on the basic level - this is how it should be done without advanced binding.
[WpfApp3.zip](https://github.com/Nucs/JsonSettings/files/6411152/WpfApp3.zip)

Key note, Collections have to be initialized empty, otherwise every load you'll end up with 5 more items (count: 5 in constructor).
So you have to dynamically do it like in the example.

**Comment by ghost1372** [comment]
Arigato 
My problem was completely solved, I think this issue can be closed
