### ISSUE TITLE
Formatting.Indented

### ISSUE THREAD

**Issue by ghost1372** [Nucs/JsonSettings#24]
after installing version 2 Alpha3 It seems that Formatting.Indented does not work 
version 2 alpha 3
![1](https://user-images.githubusercontent.com/9213496/116786313-26b20180-aab3-11eb-9df7-98687b55e173.png)

version 2 alpha 2

![0](https://user-images.githubusercontent.com/9213496/116786303-14d05e80-aab3-11eb-9d3c-192bf8231b74.png)

Is there an option to enable it?

**Comment by Nucs** [comment]
![image](https://user-images.githubusercontent.com/649919/116803716-d83c4b80-ab22-11eb-8f4a-21bf537b0138.png)
Formatting is passed via JsonSerializerSettings. The picture shows you the resolving logic.
By default, all `JsonSettings` use static `JsonSettings.SerializationSettings` which has `Formatting` property with default value of `Formatting.Indented`.
In-order to override setting specifically for an object, use instance `mySettings.OverrideSerializerSettings` or modify static `JsonSettings.SerializationSettings`.

Note that on next release it'll work appropriately. on release 2.0.0-alpha3 I accidentally override the Formatting.
