### ISSUE TITLE
Exception error for virtual proeprty in AutoSave

### ISSUE THREAD

**Issue by ghost1372** [Nucs/JsonSettings#27]
I always use the auto save module and I sometimes forget to define the properties virtual for AutoSave, I get into trouble when working with the program and look for the cause of the problem for a while Until I realize that the property is not defined virtual
It would be nice to have an exception error in this case That we can understand that the property is not virtual

**Comment by Nucs** [comment]
Today I discovered that if a property is not virtual then the proxy ignores it's value when it creates another object.
Therefore there is logic to enforcing all properties to be virtual even if IgnoreJsonAttribute or IgnoreAutosaveAttribute is specified in order to properly auto-save.

**Comment by Nucs** [comment]
This is now enforced as of release alpha4.
