### ISSUE TITLE
Simplify WithVersioning Module 

### ISSUE THREAD

**Issue by ghost1372** [Nucs/JsonSettings#28]
Is it possible to change the version number only in the config class?
Using
```
public virtual Version Version { get; set; } = new Version(1, 0, 0, 6);

.WithVersioning(VersioningResultAction.RenameAndLoadDefault)
```
instead of
`.WithVersioning("2.1.1.7", VersioningResultAction.RenameAndLoadDefault)
`
In this case, the way to use the module is also easier and the possibility of mistakes in the version number is also reduced

Thank you

**Comment by Nucs** [comment]
The main challenge is that to get that default value, we'll have to allocate a new object to obtain it.
Maybe a better option will be to use an attribute 
```C#
[EnforcedVersion(new Version(...))] //or with string
public virtual Version Version { get; set; }
```

The value will be populated only if VersioningModule is attached.

**Comment by ghost1372** [comment]
Attribute seems interesting
I agree with you

**Comment by Nucs** [comment]
[JsonSettings.Tests/VersioningModuleTests.cs](https://github.com/Nucs/JsonSettings/blob/master/tests/JsonSettings.Tests/VersioningModuleTests.cs) has tests covering usage + support for inheritance. It is the same as I mentioned above. Will be out in next prerelease
