### ISSUE TITLE
Is it Supported in UWP?

### ISSUE THREAD

**Issue by ghost1372** [Nucs/JsonSettings#30]
I have successfully installed JsonSettings on UWP Project but I get a NullRefrence error when i want to use it.

```
public static readonly string RootPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), AppName);
public static readonly string ConfigPath = Path.Combine(RootPath, "Config.json");

public class Configs : NotifiyingJsonSettings, IVersionable
    {
        public override string FileName { get; set; } = Consts.ConfigPath;

public static Configs Settings = JsonSettings.Configure<Configs>()
                                   .WithRecovery(RecoveryAction.RenameAndLoadDefault)
                                   .WithVersioning(new Version(2, 1, 0, 0), VersioningResultAction.RenameAndLoadDefault)
                                   .LoadNow()
                                   .EnableAutosave();
```
![Untitled](https://user-images.githubusercontent.com/9213496/118096811-18cf7b00-b3e7-11eb-8462-763f830b9f8f.png)

**Comment by Nucs** [comment]
Hey, I don't have a way to test it on UWP as of now.
@ghost1372 Could you please provide the callstack of that error?

**Comment by ghost1372** [comment]
If you need other information, let me know
![image](https://user-images.githubusercontent.com/9213496/118118381-17f81280-b402-11eb-8b6d-619dc0aba1d1.png)

<HTML>
<head>
<body>



  | Name | Value | Type
-- | -- | -- | --
◢ | $exception | {"Object reference not set to an instance of an object."} | System.NullReferenceException
  | ▶ Data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | HResult | -2147467261 | int
  | HelpLink | null | string
  | ◢ InnerException | null | System.Exception
  | ▶ Static members |   |  
  | Message | "Object reference not set to an instance of an object." | string
  | Source | "JsonSettings" | string
  | StackTrace | "   at Nucs.JsonSettings.JsonSettings.Save(Type inType, Object boxedJsonSettings, String filename)\r\n   at Nucs.JsonSettings.JsonSettings.Save(String filename)\r\n   at Nucs.JsonSettings.JsonSettings.Load(Object instance, Action configure, String filename)\r\n   at Nucs.JsonSettings.JsonSettings.Load[T](T instance, Action configure, String filename)\r\n   at Nucs.JsonSettings.Fluent.FluentJsonSettings.LoadNow[T](T _instance)\r\n   at HandyWinget.Helper..cctor() in D:\\Programming\\C#\\HandyWinGet\\HandyWinget\\src\\HandyWinget\\Helper\\Helper.cs:line 16" | string
  | ◢ TargetSite | {Void Save(System.Type, System.Object, System.String)} | System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
  | Attributes | Public \| Static \| HideBySig | System.Reflection.MethodAttributes
  | CallingConvention | Standard | System.Reflection.CallingConventions
  | ContainsGenericParameters | false | bool
  | CustomAttributes | Method System.Reflection.MemberInfo.get_CustomAttributes cannot be called in this context. | System.Collections.Generic.IEnumerable<System.Reflection.CustomAttributeData>
  | ▶ DeclaringType | {Name = "JsonSettings" FullName = "Nucs.JsonSettings.JsonSettings"} | System.Type {System.RuntimeType}
  | IsAbstract | false | bool
  | IsAssembly | false | bool
  | IsConstructedGenericMethod | Method System.Reflection.MethodBase.get_IsConstructedGenericMethod cannot be called in this context. | bool
  | IsConstructor | false | bool
  | IsFamily | false | bool
  | IsFamilyAndAssembly | false | bool
  | IsFamilyOrAssembly | false | bool
  | IsFinal | false | bool
  | IsGenericMethod | false | bool
  | IsGenericMethodDefinition | false | bool
  | IsHideBySig | true | bool
  | IsPrivate | false | bool
  | IsPublic | true | bool
  | IsSecurityCritical | Method System.Reflection.RuntimeMethodInfo.get_IsSecurityCritical cannot be called in this context. | bool
  | IsSecuritySafeCritical | Method System.Reflection.RuntimeMethodInfo.get_IsSecuritySafeCritical cannot be called in this context. | bool
  | IsSecurityTransparent | Method System.Reflection.RuntimeMethodInfo.get_IsSecurityTransparent cannot be called in this context. | bool
  | IsSpecialName | false | bool
  | IsStatic | true | bool
  | IsVirtual | false | bool
  | MemberType | Method | System.Reflection.MemberTypes
  | MetadataToken | 100663469 | int
  | ▶ MethodHandle | {System.RuntimeMethodHandle} | System.RuntimeMethodHandle
  | MethodImplementationFlags | Method System.Reflection.MethodBase.get_MethodImplementationFlags cannot be called in this context. | System.Reflection.MethodImplAttributes
  | ▶ Module | {JsonSettings.dll} | System.Reflection.Module {System.Reflection.RuntimeModule}
  | Name | "Save" | string
  | ▶ ReflectedType | '((System.Reflection.RuntimeMethodInfo)($exception).TargetSite).ReflectedType' threw an exception of type 'System.NotSupportedException' | System.Type {System.NotSupportedException}
  | ▶ ReturnParameter | {System.Void } | System.Reflection.ParameterInfo
  | ▶ ReturnType | {Name = "Void" FullName = "System.Void"} | System.Type {System.RuntimeType}
  | ReturnTypeCustomAttributes | Method System.Reflection.RuntimeMethodInfo.get_ReturnTypeCustomAttributes cannot be called in this context. | System.Reflection.ICustomAttributeProvider
  | ▶ Non-Public members |   |  
  | ▶ Static members |   |  
  | ▶ Non-Public members |   |  



</body>
</HTML>

**Comment by ghost1372** [comment]
@Nucs  I found the cause of the problem This does not seem to be a bug
As you can see, jsonSettings returns the null value in **UnauthorizedAccessException** 
I noticed that the UWP program does not have access to all the folders However, I have not been able to use it properly yet
Also, why is the null value returned instead of the throwing Exception So we can better understand the problem?
![image](https://user-images.githubusercontent.com/9213496/118398838-8f7ea980-b66f-11eb-9f33-d4e07a99aa6b.png)

**Comment by ghost1372** [comment]
There are codes in [Microsoft documents](https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions) that easily create files, Is there a need to write a separate module for UWP with these codes?

**Comment by Nucs** [comment]
> Also, why is the null value returned instead of the throwing Exception So we can better understand the problem?

There used to be a fallback to load default when null is returned. I removed `UnauthorizedAccessException` as this is something the user should handle. Its wrapped in JsonSettingsException now as inner exception.
I'm also adding a new test project target UWP.

**Comment by Nucs** [comment]
To my understanding UWP has its own layer for file IO but when writing in target .netstandard, will `File.Open` work if the UWP app specifies permissions in the manifest to the settings file path or does it have to be done explicitly through `FileIO`?

If the user can specify permission in the app manifest and then UnauthorizedAccessException shouldn't be thrown, so its the user's responsibility to make sure the path is accessible before accessing the library.

If it has to be done explicitly through `FileIO` then I'll create a new project and nuget package and will make a `protected virtual Stream LoadFileStream and SaveFileStream` which `UwpJsonSettings` class will have it's implementation.

**Comment by ghost1372** [comment]
Naturally .NETStandard should support read and write in UWP, but currently the File class is not supported. A few days ago I checked this and found that user permission only work for **FileIO** class And at the moment the **System.Io.File** class is not Supported.( I also tested with **broadFileSystemAccess** ([This is a restricted capability](https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions)) ) Normally FileIO only has access to a few specific folders And if we want to access other folders, we must use the FilePicker or broadFileSystemAccess 
The only way is to use a separate project and FileIo class

**Comment by Nucs** [comment]
For wider support, `UwpJsonSettings` can have `SaveAs` and `LoadFrom` overloads which prompts user to load/saveas.

**Comment by ghost1372** [comment]
any news?

**Comment by Nucs** [comment]
@ghost1372 I'm unable to properly set up a UWP project and get this working. As of now I can't add this support.
Any help will be welcome.

**Comment by ghost1372** [comment]
Oh, so I'm trying to see if I can do this myself or not

**Comment by Nucs** [comment]
I've pushed whatever I've got up so for.

**Comment by ghost1372** [comment]
Thank you, I'll check

**Comment by ghost1372** [comment]
I did a little research, your solution was interesting and simple

```

    public abstract class UwpJsonSettings : Nucs.JsonSettings.JsonSettings {
        #region Overrides of JsonSettings

        public override void Save(string filename) {
            //TODO: ask for permission here
            base.Save(filename);
        }

        #endregion
    }
}
```
But there are two points, First, there is no way to ask for permission (except folderpicker), and it must be managed with a try/cache
Second, The contents of the json file do not appear to be available in the save method (I'm not a very good programmer😅) If available, the following code should resolve the issue (However, the LoadJson method must also be overridden)

```
public async override void Save(string filename)
        {
            try
            {
                await PathIO.WriteTextAsync(filename, this);
            }
            catch (UnauthorizedAccessException)
            {
                Windows.Storage.StorageFolder storageFolder = Windows.Storage.ApplicationData.Current.LocalFolder;
                var name = Path.GetFileName(filename);
                Windows.Storage.StorageFile sampleFile = await storageFolder.CreateFileAsync(name, CreationCollisionOption.ReplaceExisting);
                await Windows.Storage.FileIO.WriteTextAsync(sampleFile, this);
            }
        }
```

I expected **this** to contain content here, but it did not
developer may have enabled unlimited access to their application, in which case the following code is work
` await PathIO.WriteTextAsync(filename, this);
`
If the developer does not have full access, we can use the default location of the application itself, which does not require access
```
Windows.Storage.StorageFolder storageFolder = Windows.Storage.ApplicationData.Current.LocalFolder;
                var name = Path.GetFileName(filename);
                Windows.Storage.StorageFile sampleFile = await storageFolder.CreateFileAsync(name, CreationCollisionOption.ReplaceExisting);
                await Windows.Storage.FileIO.WriteTextAsync(sampleFile, this);
```
And if the developer wants to specify location by the folderpicker, we have to consider another case.
anyway, It does not seem to be appropriate to use this method, JsonSettings and Files class seem to need to be rewritten for UWP.
Do you have any advice on this?

**Comment by ghost1372** [comment]
I was finally able to save and retrieve information today (Currently only the file is stored in the **ApplicationData.Current.LocalFolder** path which does not require access) 😁 You can see the changes [here](https://github.com/ghost1372/JsonSettings/commit/61a7cbce8edee66744f9b6ba2cb526c2bc7b130c)
Of course, many issues need to be resolved:
Save in any place (with permission)
Versioning module (rename and delete file)

Also, did I use the correct method for reading and writing?
