### ISSUE TITLE
difference between these

### ISSUE THREAD

**Issue by ghost1372** [Nucs/JsonSettings#4]
hi whats difference between these two?
`SettingsBag Settings = JsonSettings.Load<SettingsBag>("config.json").EnableAutosave();
`
`SettingsBag Settings { get; } = JsonSettings.Construct<SettingsBag>("config.json").EnableAutosave().LoadNow();`

**Comment by Nucs** [comment]
`EnableAutosave` is a feature of `SettingsBag` and is **NOT** a module. so it doesn't matter when you enable/call it.

Construct and LoadNow(); is used to load modules into the settings class ([see modules in wiki](https://github.com/Nucs/JsonSettings/wiki/Modules)).

For example: if your file is supposed to be encrypted using WithEncryption("pass") module, you need to **first** load the module and only **then** load the file (just like on the second example).
```C#
JsonSettings.Construct<SettingsBag>("config.json").EnableAutosave().WithEncryption("pass").LoadNow();```

**Comment by ghost1372** [comment]
tnx
