### ISSUE TITLE
update dependency

### ISSUE THREAD

**Issue by ghost1372** [Nucs/JsonSettings#42]
hi
can you upload a new nuget package with update dependency like Castle.Core?
you are using
<PackageReference Include="Castle.Core" Version="4.4.1" />
<PackageReference Include="Newtonsoft.Json" Version="12.0.3" />

but latest version is 
castel : **5.1.1**
json: 13.0.3

**Comment by Nucs** [comment]
Unless Castle 5.1.1 has some breaking changes, you should be able to upgrade to that version.
The nuget is dependent as a minimal version.

**Comment by Nucs** [comment]
I undestand, try installing the newer Castle version regardless to JsonSettings. You should be able to upgrade.
I will upgrade the version later on today/this week.

**Comment by ghost1372** [comment]
any update?

**Comment by Nucs** [comment]
I've released JsonSettings 2.0.2

**Comment by ghost1372** [comment]
Thank you so much
