### ISSUE TITLE
Autosave in hardcoded Setting file

### ISSUE THREAD

**Issue by ghost1372** [Nucs/JsonSettings#6]
is it possible to use auto save method in hardcoded mode?

**Comment by Nucs** [comment]
As the `Readme.md` says, "note: can be applied only to dynamic settings. proxy-classes are not .net-wide yet."

I wrote that quite long time ago and now it seems that there is a support with [DynamicProxy in CastleProject](https://github.com/castleproject/Core).
I'll work that on the weekend, thanks for the suggestion.

**Comment by Nucs** [comment]
Added and uploaded to version 1.0.7 and 1.0.0 of `Nucs.JsonSettings.Autosave`.
Example:
```C#
var x = JsonSettings.Load<Settings>().EnableAutosave();
x.Property = "abc"; //saved.
```
Remarks:
* All properties must be `virtual`.
* Settings class mustn't be a nested class.

I will soon add a new page to wiki.
