### ISSUE TITLE
How to use Autosave in Hardcoded Setting file

### ISSUE THREAD

**Issue by ghost1372** [Nucs/JsonSettings#7]
hi again, tnx for update, i have problem can you explain more about how to use?
this code is fine
`var x = JsonSettings.Load<mysetting>("config.json").EnableAutosave();`
but i need to use like this 
`public static JsonSettings Settings = JsonSettings.Load<mysetting>("config.json").EnableAutosave();
`problem is i cant access my prop like this:
x.myprop

**Comment by Nucs** [comment]
Hey, 
`EnableAutosave();` returns what ever you feed it, so if its `mysetting `then it'll return `mysetting`.
Simply change the declaration and loading to this:
`public static **mysetting** Settings = JsonSettings.Load<mysetting>("config.json").EnableAutosave();`

**Comment by ghost1372** [comment]
tnx problem solved
