### ISSUE TITLE
Any update on autosaving hardcoded settings? 

### ISSUE THREAD

**Issue by Sinjai** [Nucs/JsonSettings#8]
The tl;dr says it's not supported, and from my testing that's true, but there's a GitHub issue that seems to say it is supported.

**Comment by Nucs** [comment]
See #7.
I've since updated the tl;dr.

**Comment by Sinjai** [comment]
I don't have the time to re-test, but if you say it's supported then it's supported. I must've been doing something stupid. Thanks for updating the documentation and writing this useful framework -- though the fact that the namespace is lowercase makes me cry every time I see it.
