### ISSUE TITLE
default value

### ISSUE THREAD

**Issue by ghost1372** [Nucs/JsonSettings#9]
hi can you add default value Property?
something like this:
[DefaultValue=False]
 public virtual bool CredentialLogin { get; set; }

[DefaultValue="Test"]
 public virtual bool StringLocation { get; set; }

**Comment by Nucs** [comment]
Default values are done by setting the property value during construction.
This will work:

``` C#
public virtual bool CredentialLogin { get; set; } = false;
public virtual bool CredentialLogin2 { get; set; } = true;
public virtual string StringLocation { get; set; } = "somepath";

```
or
``` C#
public virtual bool CredentialLogin { get; set; };
public virtual bool CredentialLogin2 { get; set; };
public virtual string StringLocation { get; set; };

public classname() {
    CredentialLogin = false;
    CredentialLogin2 = true;
    StringLocation = "somepath";
}

```

**Comment by ghost1372** [comment]
tnx this way worked 
`public virtual bool CredentialLogin { get; set; } = false;
`
but this way not worked
```
public classname() {
    CredentialLogin = false;
    CredentialLogin2 = true;
    StringLocation = "somepath";
}
```
If you change the settings, after restarting the program, all the settings will reset to default.
